import{a as w,S as L,i as d}from"./assets/vendor-CvqES1H9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();document.querySelector(".load-btn");async function p(e,r){try{return(await w.get("https://pixabay.com/api/",{params:{key:"49069993-51884dcb47f371bf5faecc40d",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})).data}catch(s){console.error("Error:",s)}}const S=document.querySelector(".gallery"),q=document.querySelector(".load-btn");let h=0;const x=e=>{const{hits:r}=e;return h=e.totalHits,r.length===0&&(d.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",position:"topRight",backgroundColor:"red"}),q.style.display="none"),r.map(({webformatURL:s,largeImageURL:a,tags:t,likes:o,views:n,comments:b,downloads:v})=>`
            <li class="gallery-item"><div class="box">
                <a href="${a}" target="_blank">
                    <img class="gallery-img" src="${s}" alt="${t}" loading="lazy" />
                </a>
                <div class="description">
                    <div><p>Likes</p><span> ${o}</span></div>
                    <div><p>Views</p><span> ${n}</span></div>
                    <div><p>Comments</p><span> ${b}</span></div>
                    <div><p>Downloads</p><span> ${v}</span></div>
                </div>
            </div></li>`).join("")},u=e=>{const r=x(e);S.insertAdjacentHTML("beforeend",r)},P=new L(".gallery a"),g=()=>{P.refresh()},m=document.querySelector("form"),y=document.querySelector(".gallery"),c=document.querySelector(".load-btn");c.style.display="none";let i="",l=1;function $(){m.addEventListener("submit",async e=>{if(e.preventDefault(),i=new FormData(e.target).get("search"),!i){d.error({message:"Input is empty!",messageColor:"white",position:"topRight",backgroundColor:"red"});return}c.insertAdjacentHTML("afterend","<span class='loader'></span>"),m.reset();try{const s=await p(i,l);y.innerHTML="",u(s),g(),f()}catch(s){console.error("Error:",s),y.innerHTML=""}}),c.addEventListener("click",async()=>{try{l+=1;const e=await p(i,l);u(e),g(),f(),C()}catch(e){console.error("Error:",e)}})}function f(){document.querySelectorAll(".box").length>=h?d.error({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",position:"topRight",backgroundColor:"red"}):c.style.display="block"}function C(){const e=document.querySelector(".box");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}$();
//# sourceMappingURL=index.js.map
