import{a as w,S,i as d}from"./assets/vendor-CvqES1H9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const $=document.getElementById("loadbtn");async function m(e,t){try{const n=await w.get("https://pixabay.com/api/",{params:{key:"49069993-51884dcb47f371bf5faecc40d",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:40}});return $.style.display="block",n.data}catch(n){console.error("Error:",n)}}const q=document.querySelector(".gallery"),x=document.getElementById("loadbtn");let b=0;const B=e=>{const{hits:t}=e;return b=e.totalHits,t.length===0&&(console.log("No more images found. Removing loader."),I(),x.style.display="none",d.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",position:"topRight",backgroundColor:"red"})),t.map(({webformatURL:n,largeImageURL:i,tags:o,likes:r,views:s,comments:v,downloads:L})=>`
            <li class="gallery-item"><div class="box">
                <a href="${i}" target="_blank">
                    <img class="gallery-img" src="${n}" alt="${o}" loading="lazy" />
                </a>
                <div class="description">
                    <div><p>Likes</p><span> ${r}</span></div>
                    <div><p>Views</p><span> ${s}</span></div>
                    <div><p>Comments</p><span> ${v}</span></div>
                    <div><p>Downloads</p><span> ${L}</span></div>
                </div>
            </div></li>`).join("")},u=e=>{const t=B(e);q.insertAdjacentHTML("beforeend",t)},E=new S(".gallery a"),g=()=>{E.refresh()};function I(){const e=document.querySelector(".loader");e&&e.remove()}const p=document.querySelector("form"),y=document.querySelector(".gallery"),a=document.getElementById("loadbtn");a.style.display="none";let l="",c=1;function P(){p.addEventListener("submit",async e=>{if(e.preventDefault(),h(),a.insertAdjacentHTML("beforebegin","<span class='loader'></span>"),l=new FormData(e.target).get("search"),!l){d.error({message:"Input is empty!",messageColor:"white",position:"topRight",backgroundColor:"red"}),h();return}p.reset(),c=1;try{const n=await m(l,c);y.innerHTML="",u(n),g(),f()}catch(n){console.error("Error:",n),y.innerHTML=""}}),a.addEventListener("click",async()=>{c+=1;try{const e=await m(l,c);u(e),g(),f(),C()}catch(e){console.error("Error:",e)}})}function C(){const e=document.querySelector(".box");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}function f(){document.querySelectorAll(".box").length>=b?(d.error({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",position:"topRight",backgroundColor:"red"}),a.style.display="none"):a.style.display="block"}function h(){const e=document.querySelector(".loader");e&&e.remove()}P();
//# sourceMappingURL=index.js.map
