import{a as w,S,i as d}from"./assets/vendor-CvqES1H9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const $=document.getElementById("loadbtn");async function u(e,o){try{const s=await w.get("https://pixabay.com/api/",{params:{key:"49069993-51884dcb47f371bf5faecc40d",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:40}});return $.style.display="block",s.data}catch(s){console.error("Error:",s)}}const q=document.querySelector(".gallery"),x=document.getElementById("loadbtn");let b=0;const B=e=>{const{hits:o}=e;return b=e.totalHits,o.length===0&&(I(),x.style.display="none",d.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",position:"topRight",backgroundColor:"red"})),o.map(({webformatURL:s,largeImageURL:i,tags:t,likes:r,views:n,comments:v,downloads:L})=>`
            <li class="gallery-item"><div class="box">
                <a href="${i}" target="_blank">
                    <img class="gallery-img" src="${s}" alt="${t}" loading="lazy" />
                </a>
                <div class="description">
                    <div><p>Likes</p><span> ${r}</span></div>
                    <div><p>Views</p><span> ${n}</span></div>
                    <div><p>Comments</p><span> ${v}</span></div>
                    <div><p>Downloads</p><span> ${L}</span></div>
                </div>
            </div></li>`).join("")},m=e=>{const o=B(e);q.insertAdjacentHTML("beforeend",o)},E=new S(".gallery a"),p=()=>{E.refresh()};function I(){const e=document.querySelector(".loader");e&&e.remove()}const g=document.querySelector("form"),y=document.querySelector(".gallery"),a=document.getElementById("loadbtn");a.style.display="none";let l="",c=1;function P(){g.addEventListener("submit",async e=>{if(e.preventDefault(),h(),a.insertAdjacentHTML("beforebegin","<span class='loader'></span>"),l=new FormData(e.target).get("search"),!l){d.error({message:"Input is empty!",messageColor:"white",position:"topRight",backgroundColor:"red"}),h();return}g.reset(),c=1;try{const s=await u(l,c);y.innerHTML="",m(s),p(),f()}catch(s){console.error("Error:",s),y.innerHTML=""}}),a.addEventListener("click",async()=>{c+=1;try{const e=await u(l,c);m(e),p(),f(),C()}catch(e){console.error("Error:",e)}})}function C(){const e=document.querySelector(".box");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}function f(){document.querySelectorAll(".box").length>=b?(d.error({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",position:"topRight",backgroundColor:"red"}),a.style.display="none"):a.style.display="block"}function h(){const e=document.querySelector(".loader");e&&e.remove()}P();
//# sourceMappingURL=index.js.map
